# Generated by Django 5.0.2 on 2024-02-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthbuddy', '0003_doctor_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
    ]
