# Generated by Django 5.0.2 on 2024-02-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'ordering': ['created_at'], 'verbose_name': 'Massage', 'verbose_name_plural': 'Massages'},
        ),
    ]
