# Generated by Django 5.0.1 on 2024-02-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={},
        ),
    ]
