# Generated by Django 5.0.2 on 2024-02-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='host',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='participent',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
