# Generated by Django 5.0.2 on 2024-02-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_disease_user_name_user_pos_alter_user_email_rooms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
